When editing a file, selectors modified to limit number of selections to 1 for doc_class, gpo and security, and to allow higher limits for other selectors using hidden input tags to specify the limits.  Addition to POST/GET data avoided by omitting the name attribute on these hidden input tags; unique ids are used to allow JavaScript to find the value attribute of each hidden tag and associate it with the correct select tag.  JavaScript to enforce maximum number of selections on each selector.
Results of last run, after selecting an existing document to edit, changing metadata, then submitting

Saving document as E:/as/daybook_files/yc0/041/c0041hzl.101.3.txt

Appending log file E:/as/edit_log_for_root_kjbfgv5g52eubl9poinl5ihpld.txt

Hello ROOT. LOGOUT You may edit documents with ids matching patterns: '*'

Filling selection lists from server file E:/as/selectors_file_for_root_kjbfgv5g52eubl9poinl5ihpld.txt

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 38

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 20

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 51

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 20

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 62

Warning: Invalid argument supplied for foreach() in W:\new_alpha_system\cgi-bin\search_formd.php on line 20
Daybook permanent index query: select * from headerb where doc_id like "C0041HZL101" and issue_date like "200119" and title like "NEW PRINCIPLES FOR WORLD PEACE" and doc_class in () and gpo in () and security in () and (sys_code00 in ('95','97','94','92') or sys_code01 in ('95','97','94','92') or sys_code02 in ('95','97','94','92') or sys_code03 in ('95','97','94','92')) and (topic_code00 in ('210045','530000') or topic_code01 in ('210045','530000')) order by doc_id asc limit 0, 1000

By default, the first 1000 headers found will be shown. If a different range is desired, enter the number of headers to be skipped before the 1000 that will be shown, if they exist, or enter a smaller "max. number of headers".

Query failed. Errormessage: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') and gpo in () and security in () and (sys_code00 in ('95','97','94','92') or ' at line 1
Fatal error: Uncaught Error: Call to a member function fetch_row() on bool in W:\new_alpha_system\cgi-bin\search_formd.php:237 Stack trace: #0 W:\new_alpha_system\cgi-bin\search_formd.php(628): search_form::process_query(Object(mysqli), 'select count(*)...', 'select * from h...', 0) #1 W:\new_alpha_system\cgi-bin\qdd.php(239): search_form::process_form() #2 {main} thrown in W:\new_alpha_system\cgi-bin\search_formd.php on line 237